version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  forum-app:
    build: .
    container_name: forum_warframe_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./uploads:/root/uploads

volumes:
  postgres_data: